Added Reset File Needed for Setup and Environment Setup Instructions
MissouriMRR/ai-racing pull request #5
Opened 2023-11-15 05:49 UTC by Pyrallux

2024-01-16 20:34 UTC, Pyrallux commented
Requested changes to test_reset.py and README.md completed

2024-01-19 01:39 UTC, cjhr95 requested changes
Documentation! Yippee

2024-01-19 01:39 UTC, cjhr95 commented on tests/test_reset.py
> +class ReproduceResetRaceCondition:
Need a class docstring

2024-01-19 01:39 UTC, cjhr95 commented on tests/test_reset.py
Each function in the class will need a docstring, see the documentation website or Numpy doc for formatting

2024-01-24 00:17 UTC, cjhr95 requested changes
Don't fret too much, just some style stuff

2024-01-24 00:17 UTC, cjhr95 commented on tests/test_reset.py
> +    Contains vaious functions for interacting with the ADRL unreal environment
Class docstring needs some reformatting;
 - Needs a section for class attributes
 - Needs a section for class methods: here you write the function definition and a short description of the function

2024-01-24 00:17 UTC, cjhr95 commented on tests/test_reset.py
> +    def __init__(self, drone_name="drone_1"):
Parameter needs a type hint

2024-01-24 00:17 UTC, cjhr95 commented on tests/test_reset.py
> +        -----
Instead of Args, use Parameters;
```suggestion
        Parameters
        ------------
```

2024-01-24 00:17 UTC, cjhr95 commented on tests/test_reset.py
> +            drone_name (string) = Name of user controlled drone (defaults to 'drone_1')
Indicate type like in normal code
```suggestion
            drone_name: string = Name of user controlled drone (defaults to 'drone_1')
```

2024-01-24 00:17 UTC, cjhr95 commented on tests/test_reset.py
> +        self.is_thread_active = False
Type annotations needed

2024-01-24 00:17 UTC, cjhr95 commented on tests/test_reset.py
> +        self.is_thread_active = False
Type annotation

2024-01-24 00:17 UTC, cjhr95 commented on tests/test_reset.py
> +        """
Same deal here as before;
```suggestion
    def repeat_timer(self, callback, period: float):
        """
        Simple sleep timer
        
        Parameters
        ------------
            callback = Function to call
            period: float = Repeat interval in seconds
        """
```

2024-01-24 00:17 UTC, cjhr95 commented on tests/test_reset.py
> +        """
Passing functions into other functions is usually a no-no, but I'll trust you here

2024-01-24 00:17 UTC, cjhr95 commented on tests/test_reset.py
> +            sleep_sec (float, optional): Sleep time for loading level. Defaults to 2.0.
Same deal here;
```suggestion
    def load_level(self, level_name: string, sleep_sec: float | Optional=2.0):
        """
        Loads given simulator level.

        Parameters
        ------------
            level_name: string = Soccer_Field_Easy, Soccer_Field_Medium, ZhangJiaJie_Medium,
                Building99_Hard, Qualification_Tier_1, Qualification_Tier_2, 
                Qualification_Tier_3, Final_Tier_1, Final_Tier_2, or Final_Tier_3
            sleep_sec: float | Optional
                Sleep time for loading level. Defaults to 2.0.
```

2024-01-24 00:17 UTC, cjhr95 commented on tests/test_reset.py
> +        self.level_name = level_name
type annotation here

2024-01-24 00:17 UTC, cjhr95 commented on tests/test_reset.py
> +        """
Docstring fix? Ain't no way
```suggestion
    def start_race(self, tier: int | Optional=1):
        """
        Starts race against baseline drone

        Parameters
        ------------
            tier: int | Optional 
                Race tier determining difficulty. 
                Tier 1: Planning only; Tier 2: Perception Only; Tier 3: Planning and Perception.
        """
```

2024-01-24 00:17 UTC, cjhr95 commented on tests/test_reset.py
> +        """
```suggestion
        """
        Initializes user drone, enabling API control and arming the vehicle.
        Sets default values for trajectory tracker gains.
        """
```

2024-01-26 00:42 UTC, cjhr95 commented on tests/test_reset.py
> +        self.is_thread_active = False
oopsies, my bad

2024-01-26 00:51 UTC, cjhr95 requested changes
Class docstring

2024-01-26 00:51 UTC, cjhr95 commented on tests/test_reset.py
> +    Contains vaious functions for interacting with the ADRL unreal environment
Something along the lines of this:
```suggestion
    Contains various functions for interacting with the ADRL unreal environment
    
    Attributes
    -----------
    drone_name: str
        name of the drone
    is_thread_active: bool
        bool to see if current thread is active
    ....
    <repeat; add line for each class variable>
    
    Methods
    ----------
    repeat_timer(callback, period: float)
        basic sleep timer
    load_level(level_name: str, sleep_sec: float)
        Loads a sim level based on the passed name
     ....
    <repeat; add line for each class method>
    
```

2024-01-26 18:15 UTC, Pyrallux commented on tests/test_reset.py
> +    Contains vaious functions for interacting with the ADRL unreal environment
NGL straight up forgot about this. Sorry for wasting your time, should be completed now.

2024-01-27 17:35 UTC, cjhr95 approved these changes
Looks good boss

2024-01-27 17:38 UTC, merged